### ISSUE TITLE
'owl new' - Uncaught Error: Class '\o\u_System' not found

### ISSUE THREAD

**Issue by nelsonkhan** [joelesko/tht#1]
Installed successfully on Linux Mint 18 Cinnamon. PHP Version 7.0.

Result of running 'owl new':

+-------------------+
|      NEW APP      |
+-------------------+
PHP Fatal error:  Uncaught Error: Class '\o\u_System' not found in /home/[my-user-name]/.owl/lib/core/Runtime.php:232
Stack trace:
#0 /home/[my-user-name]/.owl/lib/core/Owl.php(1256): o\Runtime::getModule('', 'System')
#1 /home/[my-user-name]/.owl/lib/core/Owl.php(538): o\Owl::module('System')
#2 /home/[my-user-name]/.owl/lib/core/Owl.php(548): o\Owl::confirmInstall()
#3 /home/[my-user-name]/.owl/lib/core/Owl.php(158): o\Owl::installApp()
#4 /home/[my-user-name]/.owl/lib/core/Owl.php(121): o\Owl::mainCli()
#5 /home/[my-user-name]/.owl/lib/core/Owl.php(87): o\Owl::main()
#6 /home/[my-user-name]/.owl/bin/owl.php(28): o\Owl::start()
#7 {main}
  thrown in /home/[my-user-name]/.owl/lib/core/Runtime.php on line 232

Fatal error: Uncaught Error: Class '\o\u_System' not found in /home/[my-user-name]/.owl/lib/core/Runtime.php:232
Stack trace:
#0 /home/[my-user-name]/.owl/lib/core/Owl.php(1256): o\Runtime::getModule('', 'System')
#1 /home/[my-user-name]/.owl/lib/core/Owl.php(538): o\Owl::module('System')
#2 /home/[my-user-name]/.owl/lib/core/Owl.php(548): o\Owl::confirmInstall()
#3 /home/[my-user-name]/.owl/lib/core/Owl.php(158): o\Owl::installApp()
#4 /home/[my-user-name]/.owl/lib/core/Owl.php(121): o\Owl::mainCli()
#5 /home/[my-user-name]/.owl/lib/core/Owl.php(87): o\Owl::main()
#6 /home/[my-user-name]/.owl/bin/owl.php(28): o\Owl::start()
#7 {main}
  thrown in /home/[my-user-name]/.owl/lib/core/Runtime.php on line 232

**Comment by josephmagee** [comment]
I can verify the issue later today. Stay tuned..

**Comment by josephmagee** [comment]
@nelsonkhan, I've validated on a fresh VM of Linux Mint 18 Cinnamon 64-bit with PHP7.0 and PHP7.0-mbstring installed. It looks like the stack track is having issues finding the class within the .owl directory. Does the .owl directory show up when running 'll'? I'd ensure that you have that directory first, then see if there's a permissions issue (such as not being able to execute files within .owl). Let me know your findings.

**Comment by josephmagee** [comment]
Update: In using scotchbox as a localDev environment, I am seeing the same stack trace as provided above. I'm looking into it.

**Comment by joelesko** [comment]
Thanks Joseph.  I would check `core/modules/_index.php`, line 52.  That's where autoloading happens for core modules.

**Comment by joelesko** [comment]
@nelsonkhan 

Can you please edit `.owl/lib/core/modules/_index.php`.

Replace the block at line 52 with:

```
spl_autoload_register(function ($class) {
    $class = str_replace('o\\u_', '', $class);
    if (LibModules::isa($class)) {
        if ($class !== 'Perf') { Owl::module('Perf')->u_start('owl.loadModule', $class); }

        require_once($class . '.php');

        if ($class !== 'Perf') { Owl::module('Perf')->u_stop(); }
    } else {
        print "Can't autoload: $class";  
        print_r(LibModules::$files);
        exit();
    }
    
});
```

This adds an `else` block to trap the module that it can't find.

Thanks!

**Comment by josephmagee** [comment]
Following up @joelesko: it looks like this issue can be closed due to the inclusion of the recommended source before the rename to THT.

**Comment by planet17** [comment]
Hello, i think I can continue that issue?

My OS: Ubuntu 16.04
PHP: 5.6 && 7.1

I got the same error while try use:
```sh
tht new
```

I try to replace `autoload` with following:
```php
spl_autoload_register(function ($class) {
    $class = str_replace('o\\u_', '', $class);
    if (LibModules::isa($class)) {
        if ($class !== 'Perf') {
            Tht::module('Perf')->u_start('tht.loadModule', $class);
        }

        require_once($class . '.php');

        if ($class !== 'Perf') {
            Tht::module('Perf')->u_stop();
        }
    } else {
        print "Can't autoload: $class";
        print_r(LibModules::$files);
        exit();
    }

});
```

and got:
```

+-------------------+
|      NEW APP      |
+-------------------+
PHP Fatal error:  Uncaught Error: Class '\o\u_System' not found in /home/autodoc/.tht/lib/core/Runtime.php:232
Stack trace:
#0 /home/autodoc/.tht/lib/core/Tht.php(1259): o\Runtime::getModule('', 'System')
#1 /home/autodoc/.tht/lib/core/Tht.php(541): o\Tht::module('System')
#2 /home/autodoc/.tht/lib/core/Tht.php(551): o\Tht::confirmInstall()
#3 /home/autodoc/.tht/lib/core/Tht.php(161): o\Tht::installApp()
#4 /home/autodoc/.tht/lib/core/Tht.php(124): o\Tht::mainCli()
#5 /home/autodoc/.tht/lib/core/Tht.php(87): o\Tht::main()
#6 /home/autodoc/.tht/bin/tht.php(28): o\Tht::start()
#7 {main}
  thrown in /home/autodoc/.tht/lib/core/Runtime.php on line 232

Fatal error: Uncaught Error: Class '\o\u_System' not found in /home/autodoc/.tht/lib/core/Runtime.php on line 232

Error: Class '\o\u_System' not found in /home/autodoc/.tht/lib/core/Runtime.php on line 232

Call Stack:
    0.0007     379440   1. {main}() /home/autodoc/.tht/bin/tht.php:0
    0.0108     604464   2. o\Tht::start() /home/autodoc/.tht/bin/tht.php:28
    0.0108     604464   3. o\Tht::main() /home/autodoc/.tht/lib/core/Tht.php:87
    0.0206    1269096   4. o\Tht::mainCli() /home/autodoc/.tht/lib/core/Tht.php:124
    0.0208    1272360   5. o\Tht::installApp() /home/autodoc/.tht/lib/core/Tht.php:161
    0.0208    1272360   6. o\Tht::confirmInstall() /home/autodoc/.tht/lib/core/Tht.php:551
    0.0209    1272392   7. o\Tht::module() /home/autodoc/.tht/lib/core/Tht.php:541
    0.0209    1272392   8. o\Runtime::getModule() /home/autodoc/.tht/lib/core/Tht.php:1259
```
