### ISSUE TITLE
Uninitialized variable in Tht::getPhpGlobal

### ISSUE THREAD

**Issue by tiitlan** [joelesko/tht#10]
The variable `$def` is not initialized in `getPhpGlobal()`.

Line 625 in Tht.php should probably read
    return '';
?

If so, can submit a patch.

**Comment by joelesko** [comment]
The signature should actually take a 3rd argument for a default:

`static function getPhpGlobal ($g, $key, $def = '') {`

Would you mind posting what your value of `$g` was to cause this error?

Thanks!

**Comment by tiitlan** [comment]
Nice one, we have almost 12 hours time difference with you :).
Strange, I cannot reproduce the missing value anymore. Must've been something I did.
Anyways, created a pull request.
