### ISSUE TITLE
Linux install fails

### ISSUE THREAD

**Issue by captgreybeard** [joelesko/tht#32]
I have tried to install THT on linux via the curl command, as per the instructions on the Dowload & Install page.
All I get is:
Test of 'tht' command failed.

Any tips at all on troubleshooting this?

**Comment by joelesko** [comment]
Hi @captgreybeard,

Thanks for reporting this. 

Questions:

- What did the output of the script look like?
- What distro are you running?
- What version of php are you running?  (via `php -v`)

Thanks!

**Comment by captgreybeard** [comment]
Thanks for the prompt reply!

Output: 
> [ OK ] Unzip and deploy files
> [ OK ] 'tht' command created
>
> Test of 'tht' command failed.

Distro: Linux Mint 20.3 Una 
PHP 8.3.12
Running tht returns:

Command 'tht' not found, did you mean:

  command 'vht' from snap vht (0.4.3)
  command 'thg' from snap tortoisehg (6.5.1)
  command 'cht' from deb chemtool (1.6.14-5)
  command 'tth' from deb tth (4.12+ds-2)
  command 'tst' from deb pvm-examples (3.4.6-2build2)
  command 'the' from deb the (3.3~rc1-3build1)
  command 'thb' from deb pvm-examples (3.4.6-2build2)
  command 't4ht' from deb texlive-binaries (2019.20190605.51237-3ubuntu0.2)
  command 'thd' from deb triggerhappy (0.5.0-1)
  command 'ht' from deb texlive-plain-generic (2019.202000218-1)
  command 'tt' from deb treetop (1.6.8-1)
  command 'tgt' from deb tcm (2.20+TSQD-5build1)
  command 'dht' from deb pkg-haskell-tools (0.12build3)

See 'snap info <snapname>' for additional versions.

**Comment by joelesko** [comment]
Ok, more questions:
- Did you see the download progress as part of the output? Like this:
```
 -----------------
   INSTALL THT
-----------------

Downloading https://tht.dev/downloads/tht_v0_8_0.zip...
###################################### 100.0%
```

- Does the `tht` dir exist in your home dir?
- If so can you run `php ~/tht/run/tht.php`  

If that works, it's a problem with writing the `tht` alias to your profile. 
- What shell are you using?

In order, it tries to add it to the following:

~/.bash_aliases 
~/.bash_profile 
~/.profile 
~/.bashrc 
~/.zshrc 
~/.zprofile 
~/.zprofile

Or if you have the output of the first run, it should have said where it tried to write the alias to. 

Thanks!

**Comment by captgreybeard** [comment]
The full ouput of curl -s -o tht.sh https://tht.dev/install && source tht.sh

bash: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]
   INSTALL THT   
bash: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]

Downloading https://tht.dev/downloads/tht_v0_8_0.zip...
######################################################################### 100.0%

[ OK ] Unzip and deploy files
[ OK ] 'tht' command created

Test of 'tht' command failed.

I can run php ~/tht/run/tht.php manually. 
Looks like I'm having problem with aliases. (Using bash). Maybe some others, too, but it'll be much easier to troubleshoot once I've got the alias set up properly.

**Comment by captgreybeard** [comment]
Yup, now it runs. Getting an error page, but that's still progress!

**Comment by joelesko** [comment]
Great!  Feel free to post the error you're getting here.  

You can also set `DEV_ERRORS` to `true` in `lib/core/main/Tht.php` to get a full PHP stack trace and post it here.

**Comment by captgreybeard** [comment]
Once I had the alias issue fixed, I was able to troubleshoot the rest of it. Was able to get started playing with THT.

Thanks so much for getting me past that speedbump.
