### ISSUE TITLE
Fix the misnamed function on the Getting Started page.

### ISSUE THREAD

**Issue by josephmagee** [joelesko/tht#6]
Right now the[ "Colors" example ](https://tht.help/tutorials/how-to-create-a-basic-web-app)on the THT web site is using the upperCaseFirst() function call on line 27 and 30. It should be noted that the correct function name is "toUpperCaseFirst", and will throw an error for any user getting started.

Reproduction steps:
1) Create a colors.tht file in the pages directory and fill it with the example code provided on the above link.
2) Add the route to app.jcon.
3) Load the page and see the error.
4) Update the function calls to "toUpperCaseFirst" on lines 27 and 30 and reload.

**Comment by josephmagee** [comment]
Not sure if this is the optimal place to leave this, but I didn't see a THT website repository for separate issues.

**Comment by joelesko** [comment]
Thanks!  Updated the site.  I will set up a repo for the site when I get the time.
