### ISSUE TITLE
OOP and Windows support

### ISSUE THREAD

**Issue by gotzmann** [joelesko/tht#7]
Very interesting and funny project :) 

Please clarify it better - does THT support OOP and when it will be available on the Windows systems? 

I checked Roadmap out and there are no any detailed info about timing for these features.

**Comment by jlesko-nflx** [comment]
Hi @gotzmann,

I have been working mainly on the form generation and validation module, plus updates to the THT website.  That will probably get pushed up in the next couple of weeks.

It will support OOP, but I can't promise any specific timeline, since I work on this in my spare time.

Thanks :)

**Comment by joelesko** [comment]
Hi @gotzmann,

I have been working mainly on the form generation and validation module, plus updates to the THT website. That will probably get pushed up in the next couple of weeks.

It will support OOP, but I can't promise any specific timeline, since I work on this in my spare time.

Thanks :)
