### ISSUE TITLE
strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior

### ISSUE THREAD

**Issue by hacioguz** [joelesko/tht#9]
**PHP 7.3+**

Line 172 in  ...lib\core\Source.php
...
if (**strpos**($rawSource, "\r" !== false)) {

changed,

if (strpos($rawSource, "\r") !== false) {

**Comment by joelesko** [comment]
I have a bug fix in the next update.  Thanks!
